build_targets:
- commands:
  - chmod +x yourbased.sh
  - sh ./yourbased.sh
  container:
    image: yourbase/yb_ubuntu:16.04
  name: default
  environment:
  - DB=mysql
  - MYSQL_HOST={{ .Containers.IP "mysql" }}
  - DATABASE_HOST={{ .Containers.IP "mysql" }}
#   - MYSQL_URL=mysql2://root:root@{{ .Containers.IP "mysql" }}:3306/db
  - DATABASE_URL=mysql2://root:root@{{ .Containers.IP "db" }}:3306/db
  dependencies:
        containers:
          mysql:
            image: mysql/mysql-server:5.7
            environment:
              - MYSQL_ROOT_PASSWORD=root
              - MYSQL_DATABASE=db
              - MYSQL_USER=root
              - MYSQL_PASSWORD=root
            port_check:
              port: 3306
              timeout: 45
ci:
  builds:
  - build_target: default
    name: default
dependencies:
  build:
  - ruby:2.3.7
